create database CGIPractice
use CGIPractice
-- Delete table 
drop table Worker
create table Worker(
	WORKER_ID INT primary key identity,
	FIRST_NAME CHAR(25) not null,
	LAST_NAME CHAR(25) ,
	--salary int check( salary >=10000 and salary <=25000)
	SALARY int not null check (salary between 10000 and 25000),
	JOINING_DATE DATETIME ,
	--DEPARTMENT CHAR(25) check (dept ='HR' or dept ='Accts' or dept ='IT' dept='Sales')
	DEPARTMENT CHAR(25) not null check (DEPARTMENT  IN ('HR','Accts','IT','Sales'))
	)

	insert into  Worker values
	('   Ajay   ','Sood', 12000,'12/12/2022' ,'HR'),
	('  Deepak  ','Kumar', 22000, null, 'Accts'),
	('Rucha','Kumra', 18000,'09/20/2022', 'HR'),
	('Manoj','Dey', 22000,null, 'HR'),
	('Ajay','Sood', 12000,Getdate(),'Sales')



	select * from Worker
	-- ID shud be autogenerated
	-- identity

	Select first_name from Worker
	Select first_name As "Worker Name" from Worker

	Select upper(first_name) As "Worker Name" from Worker


	select first_name, trim(first_name) from worker

	select len(distinct(department)) from worker

	Select Distinct(DEPARTMENT) from Worker

	select first_name ,charindex('a', first_name) from worker
	select first_name ,charindex('a', first_name, 2) from worker
	



	select concat(trim(first_name) , ' ' , trim(last_name)) from worker


	alter table worker alter column first_name varchar(25)

	alter table worker alter column last_name varchar(25) 


	select * from worker order by trim(first_name)

	select * from worker order by trim(first_name), department desc

	select * from worker where first_name IN('Ajay', 'Deepak')

	select * from worker where first_name NOT IN('Ajay', 'Deepak')

	select * from worker where DEPARTMENT LIKE 'Accts'

	select * from worker where  first_name LIKE '%a%'

	select * from worker where first_name LIKE '%a'

	select * from worker where first_name LIKE '_____h'

	select * from worker where salary between 10000 and 15000
	
	select * from worker where month(JOINING_DATE) =09 and year(joining_date) = 2022  

 select Getdate()
 select convert(varchar , getdate())
 select convert(varchar , getdate(), 101)
 select convert(varchar , getdate(), 102)

 select month(getDate())
 select DATENAME(MM,getdate())
 select DATENAME(mm,getdate())
 select DATENAME(M,getdate())
 select datepart(mm, getdate())




 select count(distinct(department)) from worker